### PR TITLE
feat: Ladder gravity and point_viewcontrol

### PR DESCRIPTION
**Pull request by Rushaway**

### CODE REVIEW

**Comment by maximee-leroyy** [comment]
wow, did you find this by yourself and is it well tested?

**Comment by Rushaway** [comment]
Not tested atm, this content come from @zaCade. It's already in use on Unloze
The fix for player movement [make this plugin](https://github.com/srcdslab/sm-plugin-FixLadderGravity) not more needed

**Comment by maximee-leroyy** [comment]
oh okay and do you have a repo url where this has been updated? or is it private?

**Comment by Rushaway** [comment]
This is not private, they just dont push anything to any repo.. Bcs they do not care about open source stuff.. 😮‍💨

**Comment by maximee-leroyy** [comment]
okay lets give it a try

**Pull request merged**
